#spring.datasource.url=jdbc:postgresql://localhost:5432/bdstakeindep
#spring.datasource.username=postgres
#spring.datasource.password=postgres

spring.datasource.url=jdbc:postgresql://cfls9h51f4i86c.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d237j7593i4h8f
spring.datasource.username=u8odl5ul5e8ntc
spring.datasource.password=p1bc4c8c78d82b346ba2a591cdd7c7118302c609c50bf462e6400dc4aae034f56
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQLQuery = debug
#necesario para ocultar  el error
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect

spring.jackson.time-zone=America/Lima
spring.jackson.locale=es_PE

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.port=${PORT:8080}